/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package NewApp;

import controller.ProjectController;
import java.util.List;
import model.Project;

public class App {
    public String getGreeting() {
        return null;
    }

    public static void main(String[] args) {
        
        ProjectController projectController = new ProjectController();
        
        Project project = new Project();
        project.setName("Projeto Teste");
        project.setDescription("Descrição");
        projectController.save(project);
        
//        project.setName("Novo nome para o projeto");
//        projectController.update(project);
        
 //       List<Project> projects = projectController.getAll();
 //       System.out.println("Total de projetos = " + projects.size());
        
    }
}
